# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - db/**/*
    - config/**/*
    - bin/**/*
  TargetRubyVersion: 2.2

#Style/FrozenStringLiteralComment:
# EnforcedStyle: always

Documentation:
  Enabled: false
